Added support to BXRL78

diff --git a/scripts/aliases-set b/scripts/aliases-set
--- a/scripts/aliases-set
+++ b/scripts/aliases-set
@@ -13,7 +13,7 @@
 function _bx_show_help() 
 {
   echo "Usage: source ${BASH_SOURCE[0]} <package> <version>" 
-  echo "  accepted packages: arm armfs rh850 rh850fs riscv rx "
+  echo "  accepted packages: arm armfs rh850 rh850fs riscv rl78 rx "
   echo " "  
 }
 
@@ -21,7 +21,7 @@ function _bx_show_help()
 function _bx-aliases-set() 
 {
   if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
-    echo "ERROR: the script is not being properly sourced."
+    echo "ERROR: the script is not being properly sourced." >&2
     _bx_show_help
     return 1
   fi
@@ -39,14 +39,16 @@ function _bx-aliases-set()
     RH850FS) local BX_ARCH=rh850;;
     RISCV) local BX_ARCH=riscv;;
     RISCVFS) local BX_ARCH=riscv;;
+    RL78) local BX_ARCH=rl78;;
+    RL78FS) local BX_ARCH=rl78;;
     RX) local BX_ARCH=rx;;
     RXFS) local BX_ARCH=rx;;
-    *) echo "ERROR: specified <package> parameter is not accepted -- (${1^^})."; return 1;;
+    *) echo "ERROR: specified <package> parameter is not accepted -- (${1^^})." >&2; return 1;;
   esac
   
   # Check valid semantic version
   if [[ ${2} =~ [^[:digit:].] ]]; then
-    echo "ERROR: specified <version> parameter must only include numbers and a dot ( . ) as separator -- (${2})."
+    echo "ERROR: specified <version> parameter must only include numbers and a dot ( . ) as separator -- (${2})." >&2
     return 1
   fi
   
@@ -54,7 +56,7 @@ function _bx-aliases-set()
   declare -a BX_DOCKER_IMAGES_LIST=($(docker images iarsystems/bx${1,,} | tail -n +2 | awk '{print $1}' | cut -f2 -d/ ))
   declare -a BX_DOCKER_VERSION_LIST=($(docker images iarsystems/bx${1,,}:${2} | tail -n +2 | awk '{print $2}'))
   if [ -z ${BX_DOCKER_IMAGES_LIST} ] || [ -z ${BX_DOCKER_VERSION_LIST} ]; then
-    echo "ERROR: no Docker image was found -- iarsystems/bx${1,,}:${2}."
+    echo "ERROR: no Docker image was found -- iarsystems/bx${1,,}:${2}." >&2
     local CURRENT_IMAGES=$(docker images iarsystems/bx* | tail -n +2 | awk '{print $1":"$2}')
     if [[ ! -z ${CURRENT_IMAGES} ]]; then
       echo "IAR Build Tools Docker images found in this host:"
diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -11,19 +11,19 @@
 #
 
 function _bx_show_help() {
-  echo "Usage: ${BASH_SOURCE[0]} <path-to>/bx<package>.deb" 
+  echo "Usage: ${BASH_SOURCE[0]} <path-to>/bx<package>.deb [image-user[:image-group]]"
   echo " "
 }
 
 function _bx_build_docker_image()
 {
   if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
-    echo "ERROR: the script should be executed directly. Do not source."
+    echo "ERROR: the script should be executed directly. Do not source." >&2
     _bx_show_help
     return 1
   fi
   
-  if [ $# -ne 1 ]; then
+  if [ $# -lt 1 ]; then
     _bx_show_help
     return 1
   fi
@@ -35,11 +35,44 @@ function _bx_build_docker_image()
   local PKG_NAME=$(echo $PKG_BASE | cut -d- -f1)
   local PKG_VERSION=$(echo $PKG_BASE | cut -d- -f2)
   local IMG_TZ=$(cat /etc/timezone)
+  local IMG_USER_GROUP=$2
+  local IMG_USER
+  local IMG_GROUP
+  local IMG_USER_ID
+  local IMG_GROUP_ID
 
   if [ ! -f "${PKG_PATH}/${PKG_FILE}" ]; then
-    echo "ERROR: file [${1}] not found."
+    echo "ERROR: file [${1}] not found." >&2
     _bx_show_help
     return 1
+  fi
+
+  # Add possibility of creating a docker image with workingdir permissions
+  # For a any existing CI user:group, if specified (i.e. Jenkins)
+  # The default group is iarusers, if not specified
+  if [ -z ${IMG_USER_GROUP} ]; then
+    IMG_USER_ID=$(id -u)
+    IMG_GROUP_ID=$(grep docker /etc/group | cut -d: -f3)
+  else
+    IMG_USER=$(echo ${IMG_USER_GROUP} | cut -d: -f1)
+    IMG_GROUP=$(echo ${IMG_USER_GROUP} | cut -d: -f2)
+    if [ -z ${IMG_GROUP} ]; then
+	    IMG_GROUP=docker
+    fi
+    if [ $(grep -c "^${IMG_USER}:" /etc/passwd) == 0 ]; then
+      echo "ERROR: specified image's user [${IMG_USER}] not found." >&2
+      _bx_show_help
+      return 1
+    else
+      IMG_USER_ID=$(id -u ${IMG_USER})
+    fi
+    if [ $(grep -c "^${IMG_GROUP}:" /etc/group) == 0 ]; then
+      echo "ERROR: specified image's group [${IMG_GROUP}] not found." >&2
+      _bx_show_help
+      return 1
+    else
+      IMG_GROUP_ID=$(grep ${IMG_GROUP} /etc/group | cut -d: -f3)
+    fi
   fi
 
   case ${PKG_NAME^^} in
@@ -49,9 +82,11 @@ function _bx_build_docker_image()
     BXRH850FS) local BX_ARCH=rh850;;
     BXRISCV) local BX_ARCH=riscv;;
     BXRISCVFS) local BX_ARCH=riscv;;
+    BXRL78) local BX_ARCH=rl78;;
+    BXRL78FS) local BX_ARCH=rl78;;
     BXRX) local BX_ARCH=rx;;
     BXRXFS) local BX_ARCH=rx;;
-    *) echo "ERROR: invalid package. (${PKG_NAME^^})"; _bx_show_help; return 1;;
+    *) echo "ERROR: invalid package. (${PKG_NAME^^})" >&2; _bx_show_help; return 1;;
   esac
   
   echo "ARCH is $BX_ARCH"
@@ -61,7 +96,8 @@ function _bx_build_docker_image()
   cp -v "${PKG_PATH}/${PKG_FILE}" "${SCRIPT_PATH}/../images"
 
   echo -- Building the Docker image for ${PKG_NAME,,}-${PKG_VERSION}...
-  docker build --build-arg USER_ID=$(id -u) \
+  docker build --build-arg USER_ID=${IMG_USER_ID} \
+               --build-arg GROUP_ID=${IMG_GROUP_ID} \
                --build-arg PKG_NAME=${PKG_NAME,,} \
                --build-arg PKG_FILE=${PKG_FILE} \
                --build-arg BX_ARCH=${BX_ARCH} \
